name: Create a legacy holder snapshot

on:
  schedule:
    - cron: "05 0 * * *"
  workflow_dispatch:

jobs:
  quekz-snapshot-legacy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.9"
          no-cache: true

      - name: Snapshot WNS Holders
        run: bun run ./snapshot_legacy.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ONCHAIN_COLLECTION: BuAYoZPVwQw4AfeEpHTx6iGPbQtB27W7tJUjgyLzgiko
          IGNORED_ADDRESSES: "4zdNGgAtFsW1cQgHqkiWyRsxaAgxrSRRynnuunxzjxue,1BWutmTvYPwDtmw9abTkS4Ssr8no61spGAvW1X6NDix"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Snapshot Legacy $(date +'%Y-%m-%d')"
          git push
