name: Update WNS Hashlist

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  quekz-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.36"

      - name: Snapshot WNS Holders
        run: bun run ./generate-wns-hashlist.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTHORITY_ADDRESS: DMxV5pTgnyJW9H2Xifjcs71H29KNeqKfDVXDLhN7ADjj
          OUTPUT_PATH: ./nobles-hashlist.json

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated WNS Nobles Hashlist $(date +'%Y-%m-%d')" && git push
